<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6d3175f0-c97c-441f-8b4f-3ba3a5f790e4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Database\ECommerce.Database.csproj" />
    <ProjectReference Include="..\Product.Data\Product.Data.csproj" />
    <ProjectReference Include="..\Product.Services\Product.Services.csproj" />
  </ItemGroup>

</Project>
